import {
  CMSData,
  Student,
  ClassRole,
  Announcement,
  EventItem,
  GalleryItem,
  SiteSettings,
  TimeCapsuleMessage,
  MemoryNote,
  SuperlativeAward,
  DayScheduleItem,
  ClassMemoryPhoto,
  ClassProject,
  DeskItem,
  LabSettings,
} from '@/types';

// Helper to generate consistent avatar placeholders with cyber tech gradients
export function getStudentAvatarUrl(name: string, gender: 'L' | 'P'): string {
  const encodedName = encodeURIComponent(name);
  const bgColor = gender === 'L' ? '0284c7' : 'db2777'; // Sky Blue for L, Rose/Pink for P
  return `https://ui-avatars.com/api/?name=${encodedName}&background=${bgColor}&color=ffffff&size=256&bold=true&rounded=false`;
}

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'std-01',
    name: 'Aisyah Puspitasari',
    nisn: '0071829001',
    elective_subject: 'Cloud Computing & Cyber Security',
    major: 'Teknik Komputer dan Jaringan',
    gender: 'P',
    birth_place: 'Yogyakarta',
    birth_date: '2008-04-12',
    parent_name: 'Bambang Puspito',
    photo_url: '',
    is_active: true,
    created_at: '2026-07-15T00:00:00Z',
    updated_at: '2026-07-15T00:00:00Z',
  },
  {
    id: 'std-02',
    name: 'Alfian Aditya Syahputra',
    nisn: '0071829002',
    elective_subject: 'Network Engineering & Cisco',
    major: 'Teknik Komputer dan Jaringan',
    gender: 'L',
    birth_place: 'Sleman',
    birth_date: '2008-01-20',
    parent_name: 'Aditya Pratama',
    photo_url: '',
    is_active: true,
    created_at: '2026-07-15T00:00:00Z',
    updated_at: '2026-07-15T00:00:00Z',
  },
  {
    id: 'std-03',
    name: 'Aloysius Christian Putra Sadewa',
    nisn: '0071829003',
    elective_subject: 'Cyber Security & Ethical Hacking',
    major: 'Teknik Komputer dan Jaringan',
    gender: 'L',
    birth_place: 'Yogyakarta',
    birth_date: '2008-06-18',
    parent_name: 'Sadewa Nugroho',
    photo_url: '',
    is_active: true,
    created_at: '2026-07-15T00:00:00Z',
    updated_at: '2026-07-15T00:00:00Z',
  },
  {
    id: 'std-04',
    name: 'Alvino Daniswara Mahendra',
    nisn: '0071829004',
    elective_subject: 'IoT & Smart Network Systems',
    major: 'Teknik Komputer dan Jaringan',
    gender: 'L',
    birth_place: 'Bantul',
    birth_date: '2008-09-05',
    parent_name: 'Danis Mahendra',
    photo_url: '',
    is_active: true,
    created_at: '2026-07-15T00:00:00Z',
    updated_at: '2026-07-15T00:00:00Z',
  },
  {
    id: 'std-05',
    name: 'Alvino Revan Milano',
    nisn: '0071829005',
    elective_subject: 'Linux Server Administration',
    major: 'Teknik Komputer dan Jaringan',
    gender: 'L',
    birth_place: 'Kulon Progo',
    birth_date: '2008-02-14',
    parent_name: 'Milano Sanjaya',
    photo_url: '',
    is_active: true,
    created_at: '2026-07-15T00:00:00Z',
    updated_at: '2026-07-15T00:00:00Z',
  },
  {
    id: 'std-06',
    name: 'Angelo Jovan Valentino',
    nisn: '0071829006',
    elective_subject: 'Network Automation & Python',
    major: 'Teknik Komputer dan Jaringan',
    gender: 'L',
    birth_place: 'Yogyakarta',
    birth_date: '2008-11-23',
    parent_name: 'Valentino Ginting',
    photo_url: '',
    is_active: true,
    created_at: '2026-07-15T00:00:00Z',
    updated_at: '2026-07-15T00:00:00Z',
  },
  {
    id: 'std-07',
    name: 'Anindito Aziz Purwanto',
    nisn: '0071829007',
    elective_subject: 'Enterprise Cloud Infrastructure',
    major: 'Teknik Komputer dan Jaringan',
    gender: 'L',
    birth_place: 'Sleman',
    birth_date: '2008-03-10',
    parent_name: 'Purwanto Haryadi',
    photo_url: '',
    is_active: true,
    created_at: '2026-07-15T00:00:00Z',
    updated_at: '2026-07-15T00:00:00Z',
  },
  {
    id: 'std-08',
    name: 'Ayesha Faria Tasnim Santosa',
    nisn: '0071829008',
    elective_subject: 'DevOps & Microservices',
    major: 'Teknik Komputer dan Jaringan',
    gender: 'P',
    birth_place: 'Yogyakarta',
    birth_date: '2008-08-19',
    parent_name: 'Santosa Wijaya',
    photo_url: '',
    is_active: true,
    created_at: '2026-07-15T00:00:00Z',
    updated_at: '2026-07-15T00:00:00Z',
  },
  {
    id: 'std-09',
    name: 'Bintang Raihan Andika Bangun',
    nisn: '0071829009',
    elective_subject: 'Wireless & Optical Transmission',
    major: 'Teknik Komputer dan Jaringan',
    gender: 'L',
    birth_place: 'Medan',
    birth_date: '2008-05-17',
    parent_name: 'Andika Bangun',
    photo_url: '',
    is_active: true,
    created_at: '2026-07-15T00:00:00Z',
    updated_at: '2026-07-15T00:00:00Z',
  },
  {
    id: 'std-10',
    name: 'Daffa Aliefano Rafid Pandia',
    nisn: '0071829010',
    elective_subject: 'Cyber Defense & Security Operations',
    major: 'Teknik Komputer dan Jaringan',
    gender: 'L',
    birth_place: 'Yogyakarta',
    birth_date: '2008-07-07',
    parent_name: 'Rafid Pandia',
    photo_url: '',
    is_active: true,
    created_at: '2026-07-15T00:00:00Z',
    updated_at: '2026-07-15T00:00:00Z',
  },
  {
    id: 'std-11',
    name: 'Daffa Falah Fathin',
    nisn: '0071829011',
    elective_subject: 'MikroTik Certified Network Associate',
    major: 'Teknik Komputer dan Jaringan',
    gender: 'L',
    birth_place: 'Bantul',
    birth_date: '2008-10-11',
    parent_name: 'Fathin Syuhada',
    photo_url: '',
    is_active: true,
    created_at: '2026-07-15T00:00:00Z',
    updated_at: '2026-07-15T00:00:00Z',
  },
  {
    id: 'std-12',
    name: 'Deanda Arveza Azka Pratama',
    nisn: '0071829012',
    elective_subject: 'Virtualization & Data Center Ops',
    major: 'Teknik Komputer dan Jaringan',
    gender: 'L',
    birth_place: 'Sleman',
    birth_date: '2008-12-04',
    parent_name: 'Azka Pratama',
    photo_url: '',
    is_active: true,
    created_at: '2026-07-15T00:00:00Z',
    updated_at: '2026-07-15T00:00:00Z',
  },
  {
    id: 'std-13',
    name: 'Fabian Fauz Kurniawan',
    nisn: '0071829013',
    elective_subject: 'Network Monitoring & Syslog Systems',
    major: 'Teknik Komputer dan Jaringan',
    gender: 'L',
    birth_place: 'Yogyakarta',
    birth_date: '2008-03-29',
    parent_name: 'Kurniawan Hidayat',
    photo_url: '',
    is_active: true,
    created_at: '2026-07-15T00:00:00Z',
    updated_at: '2026-07-15T00:00:00Z',
  },
  {
    id: 'std-14',
    name: 'Fadhil Mudaffar Malikal Wicaksana',
    nisn: '0071829014',
    elective_subject: 'Cisco Routing & Switching Protocols',
    major: 'Teknik Komputer dan Jaringan',
    gender: 'L',
    birth_place: 'Gunungkidul',
    birth_date: '2008-04-16',
    parent_name: 'Wicaksana Malikal',
    photo_url: '',
    is_active: true,
    created_at: '2026-07-15T00:00:00Z',
    updated_at: '2026-07-15T00:00:00Z',
  },
  {
    id: 'std-15',
    name: 'Faiz Abdillah Aditama',
    nisn: '0071829015',
    elective_subject: 'Linux Kernel & Server Security',
    major: 'Teknik Komputer dan Jaringan',
    gender: 'L',
    birth_place: 'Yogyakarta',
    birth_date: '2008-06-25',
    parent_name: 'Aditama Surya',
    photo_url: '',
    is_active: true,
    created_at: '2026-07-15T00:00:00Z',
    updated_at: '2026-07-15T00:00:00Z',
  },
  {
    id: 'std-16',
    name: 'Faiza Afiqa Rais',
    nisn: '0071829016',
    elective_subject: 'Cloud Solutions & AWS Architecture',
    major: 'Teknik Komputer dan Jaringan',
    gender: 'P',
    birth_place: 'Sleman',
    birth_date: '2008-09-14',
    parent_name: 'Rais Abdullah',
    photo_url: '',
    is_active: true,
    created_at: '2026-07-15T00:00:00Z',
    updated_at: '2026-07-15T00:00:00Z',
  },
  {
    id: 'std-17',
    name: 'Febtriasa Putri Pinanti',
    nisn: '0071829017',
    elective_subject: 'UI/UX & Web Application Frontend',
    major: 'Teknik Komputer dan Jaringan',
    gender: 'P',
    birth_place: 'Bantul',
    birth_date: '2008-02-28',
    parent_name: 'Pinanti Utomo',
    photo_url: '',
    is_active: true,
    created_at: '2026-07-15T00:00:00Z',
    updated_at: '2026-07-15T00:00:00Z',
  },
  {
    id: 'std-18',
    name: 'Firjatullah Kumarajati Bekti Pambudi',
    nisn: '0071829018',
    elective_subject: 'Network Infrastructure Maintenance',
    major: 'Teknik Komputer dan Jaringan',
    gender: 'L',
    birth_place: 'Yogyakarta',
    birth_date: '2008-08-08',
    parent_name: 'Bekti Pambudi',
    photo_url: '',
    is_active: true,
    created_at: '2026-07-15T00:00:00Z',
    updated_at: '2026-07-15T00:00:00Z',
  },
  {
    id: 'std-19',
    name: 'Galuh Janu Alfath Thoriq',
    nisn: '0071829019',
    elective_subject: 'MikroTik Hotspot & Bandwidth Management',
    major: 'Teknik Komputer dan Jaringan',
    gender: 'L',
    birth_place: 'Sleman',
    birth_date: '2008-01-09',
    parent_name: 'Thoriq Alfath',
    photo_url: '',
    is_active: true,
    created_at: '2026-07-15T00:00:00Z',
    updated_at: '2026-07-15T00:00:00Z',
  },
  {
    id: 'std-20',
    name: 'Irsyad Zakie Mahardika',
    nisn: '0071829020',
    elective_subject: 'Database Management & PostgreSQL',
    major: 'Teknik Komputer dan Jaringan',
    gender: 'L',
    birth_place: 'Yogyakarta',
    birth_date: '2008-05-30',
    parent_name: 'Mahardika Satria',
    photo_url: '',
    is_active: true,
    created_at: '2026-07-15T00:00:00Z',
    updated_at: '2026-07-15T00:00:00Z',
  },
  {
    id: 'std-21',
    name: 'Juan Goklas Panjaitan',
    nisn: '0071829021',
    elective_subject: 'Firewall & Network Penetration Testing',
    major: 'Teknik Komputer dan Jaringan',
    gender: 'L',
    birth_place: 'Pematangsiantar',
    birth_date: '2008-07-19',
    parent_name: 'Panjaitan Marbun',
    photo_url: '',
    is_active: true,
    created_at: '2026-07-15T00:00:00Z',
    updated_at: '2026-07-15T00:00:00Z',
  },
  {
    id: 'std-22',
    name: 'Kayyasah Ardyka Syakira Najwa',
    nisn: '0071829022',
    elective_subject: 'Cloud Systems & Automation',
    major: 'Teknik Komputer dan Jaringan',
    gender: 'P',
    birth_place: 'Yogyakarta',
    birth_date: '2008-10-24',
    parent_name: 'Ardyka Najwa',
    photo_url: '',
    is_active: true,
    created_at: '2026-07-15T00:00:00Z',
    updated_at: '2026-07-15T00:00:00Z',
  },
  {
    id: 'std-23',
    name: 'Latifah Az Zahra',
    nisn: '0071829023',
    elective_subject: 'Network Security Audit & Policy',
    major: 'Teknik Komputer dan Jaringan',
    gender: 'P',
    birth_place: 'Bantul',
    birth_date: '2008-12-15',
    parent_name: 'Ahmad Az Zahra',
    photo_url: '',
    is_active: true,
    created_at: '2026-07-15T00:00:00Z',
    updated_at: '2026-07-15T00:00:00Z',
  },
  {
    id: 'std-24',
    name: 'Luna Almaghfira Nazhifa',
    nisn: '0071829024',
    elective_subject: 'Fullstack Web & API Development',
    major: 'Teknik Komputer dan Jaringan',
    gender: 'P',
    birth_place: 'Sleman',
    birth_date: '2008-04-03',
    parent_name: 'Nazhifa Hakim',
    photo_url: '',
    is_active: true,
    created_at: '2026-07-15T00:00:00Z',
    updated_at: '2026-07-15T00:00:00Z',
  },
  {
    id: 'std-25',
    name: 'Mahabbah Mahabban Romadhon',
    nisn: '0071829025',
    elective_subject: 'Server Architecture & Debian GNU/Linux',
    major: 'Teknik Komputer dan Jaringan',
    gender: 'L',
    birth_place: 'Yogyakarta',
    birth_date: '2008-09-28',
    parent_name: 'Romadhon Basri',
    photo_url: '',
    is_active: true,
    created_at: '2026-07-15T00:00:00Z',
    updated_at: '2026-07-15T00:00:00Z',
  },
  {
    id: 'std-26',
    name: 'Maheswara Shoofian Hamid',
    nisn: '0071829026',
    elective_subject: 'Cyber Security Operations & Forensics',
    major: 'Teknik Komputer dan Jaringan',
    gender: 'L',
    birth_place: 'Kulon Progo',
    birth_date: '2008-03-14',
    parent_name: 'Shoofian Hamid',
    photo_url: '',
    is_active: true,
    created_at: '2026-07-15T00:00:00Z',
    updated_at: '2026-07-15T00:00:00Z',
  },
  {
    id: 'std-27',
    name: 'Malaeka Raihaana Amira Sigit',
    nisn: '0071829027',
    elective_subject: 'Financial IT & Class Administration Systems',
    major: 'Teknik Komputer dan Jaringan',
    gender: 'P',
    birth_place: 'Yogyakarta',
    birth_date: '2008-06-06',
    parent_name: 'Sigit Purwanto',
    photo_url: '',
    is_active: true,
    created_at: '2026-07-15T00:00:00Z',
    updated_at: '2026-07-15T00:00:00Z',
  },
  {
    id: 'std-28',
    name: 'Maria Maharani Prasetyo',
    nisn: '0071829028',
    elective_subject: 'Cloud Computing & Distributed Systems',
    major: 'Teknik Komputer dan Jaringan',
    gender: 'P',
    birth_place: 'Sleman',
    birth_date: '2008-08-22',
    parent_name: 'Prasetyo Wibowo',
    photo_url: '',
    is_active: true,
    created_at: '2026-07-15T00:00:00Z',
    updated_at: '2026-07-15T00:00:00Z',
  },
  {
    id: 'std-29',
    name: 'Maylafiana Nurrizkia Setyaningrum',
    nisn: '0071829029',
    elective_subject: 'IT Project Management & Systems Analysis',
    major: 'Teknik Komputer dan Jaringan',
    gender: 'P',
    birth_place: 'Bantul',
    birth_date: '2008-11-17',
    parent_name: 'Setyaningrum Joko',
    photo_url: '',
    is_active: true,
    created_at: '2026-07-15T00:00:00Z',
    updated_at: '2026-07-15T00:00:00Z',
  },
  {
    id: 'std-30',
    name: 'Muhammad Neo Navaz Nurvagus',
    nisn: '0071829030',
    elective_subject: 'Network Automation & Software Defined Network (SDN)',
    major: 'Teknik Komputer dan Jaringan',
    gender: 'L',
    birth_place: 'Yogyakarta',
    birth_date: '2008-01-31',
    parent_name: 'Nurvagus Santoso',
    photo_url: '',
    is_active: true,
    created_at: '2026-07-15T00:00:00Z',
    updated_at: '2026-07-15T00:00:00Z',
  },
  {
    id: 'std-31',
    name: 'Nur Muhibbin',
    nisn: '0071829031',
    elective_subject: 'Fiber Optic Splicing & FTTH Network',
    major: 'Teknik Komputer dan Jaringan',
    gender: 'L',
    birth_place: 'Magelang',
    birth_date: '2008-05-12',
    parent_name: 'Muhibbin Rahmat',
    photo_url: '',
    is_active: true,
    created_at: '2026-07-15T00:00:00Z',
    updated_at: '2026-07-15T00:00:00Z',
  },
  {
    id: 'std-32',
    name: 'Oreal Ahessa Wiratmaja',
    nisn: '0071829032',
    elective_subject: 'Cisco Routing Protocols & Network Design',
    major: 'Teknik Komputer dan Jaringan',
    gender: 'L',
    birth_place: 'Yogyakarta',
    birth_date: '2008-07-27',
    parent_name: 'Wiratmaja Kusuma',
    photo_url: '',
    is_active: true,
    created_at: '2026-07-15T00:00:00Z',
    updated_at: '2026-07-15T00:00:00Z',
  },
  {
    id: 'std-33',
    name: 'Zahraa Kamila Findra Putri',
    nisn: '0071829033',
    elective_subject: 'Cyber Security Policy & Information Assurance',
    major: 'Teknik Komputer dan Jaringan',
    gender: 'P',
    birth_place: 'Sleman',
    birth_date: '2008-10-05',
    parent_name: 'Findra Putriono',
    photo_url: '',
    is_active: true,
    created_at: '2026-07-15T00:00:00Z',
    updated_at: '2026-07-15T00:00:00Z',
  },
  {
    id: 'std-34',
    name: 'Zhafira Naura As Syfa',
    nisn: '0071829034',
    elective_subject: 'Database Systems & IT Documentation',
    major: 'Teknik Komputer dan Jaringan',
    gender: 'P',
    birth_place: 'Yogyakarta',
    birth_date: '2008-12-21',
    parent_name: 'As Syfa Iskandar',
    photo_url: '',
    is_active: true,
    created_at: '2026-07-15T00:00:00Z',
    updated_at: '2026-07-15T00:00:00Z',
  },
];

export const INITIAL_ROLES: ClassRole[] = [
  // Wali Kelas
  {
    id: 'role-01',
    role_name: 'Wali Kelas',
    category: 'wali',
    person_name: 'Bu Febriyana, S.T.',
    student_id: null,
    position_order: 1,
    badge: 'Guru Pembimbing',
  },
  // Pimpinan
  {
    id: 'role-02',
    role_name: 'Ketua Kelas',
    category: 'pimpinan',
    person_name: 'Anindito Aziz Purwanto',
    student_id: 'std-07',
    position_order: 2,
    badge: 'Pimpinan Kelas',
  },
  {
    id: 'role-03',
    role_name: 'Wakil Ketua',
    category: 'pimpinan',
    person_name: 'Aloysius Christian Putra Sadewa',
    student_id: 'std-03',
    position_order: 3,
    badge: 'Pimpinan Kelas',
  },
  // Administrasi: Sekretaris
  {
    id: 'role-04',
    role_name: 'Sekretaris 1',
    category: 'administrasi',
    person_name: 'Zhafira Naura As Syfa',
    student_id: 'std-34',
    position_order: 4,
    badge: 'Administrasi',
  },
  {
    id: 'role-05',
    role_name: 'Sekretaris 2',
    category: 'administrasi',
    person_name: 'Irsyad Zakie Mahardika',
    student_id: 'std-20',
    position_order: 5,
    badge: 'Administrasi',
  },
  // Administrasi: Bendahara
  {
    id: 'role-06',
    role_name: 'Bendahara 1',
    category: 'administrasi',
    person_name: 'Malaeka Raihaana Amira Sigit',
    student_id: 'std-27',
    position_order: 6,
    badge: 'Keuangan',
  },
  {
    id: 'role-07',
    role_name: 'Bendahara 2',
    category: 'administrasi',
    person_name: 'Maylafiana Nurrizkia Setyaningrum',
    student_id: 'std-29',
    position_order: 7,
    badge: 'Keuangan',
  },
  // Komando: Danton
  {
    id: 'role-08',
    role_name: 'Komandan Peleton (Danton)',
    category: 'komando',
    person_name: 'Maheswara Shoofian Hamid',
    student_id: 'std-26',
    position_order: 8,
    badge: 'Komando Lapangan',
  },
  {
    id: 'role-09',
    role_name: 'Second Danton',
    category: 'komando',
    person_name: 'Deanda Arveza Azka Pratama',
    student_id: 'std-12',
    position_order: 9,
    badge: 'Komando Lapangan',
  },
  // Koordinator Kebersihan
  {
    id: 'role-10',
    role_name: 'Koordinator Kebersihan (1)',
    category: 'koordinator',
    person_name: 'Firjatullah Kumarajati Bekti Pambudi',
    student_id: 'std-18',
    position_order: 10,
    badge: 'Kebersihan',
  },
  {
    id: 'role-11',
    role_name: 'Koordinator Kebersihan (2)',
    category: 'koordinator',
    person_name: 'Galuh Janu Alfath Thoriq',
    student_id: 'std-19',
    position_order: 11,
    badge: 'Kebersihan',
  },
  {
    id: 'role-12',
    role_name: 'Koordinator Kebersihan (3)',
    category: 'koordinator',
    person_name: 'Fabian Fauz Kurniawan',
    student_id: 'std-13',
    position_order: 12,
    badge: 'Kebersihan',
  },
  // Koordinator Keamanan
  {
    id: 'role-13',
    role_name: 'Koordinator Keamanan (1)',
    category: 'koordinator',
    person_name: 'Daffa Aliefano Rafid Pandia',
    student_id: 'std-10',
    position_order: 13,
    badge: 'Ketertiban & Keamanan',
  },
  {
    id: 'role-14',
    role_name: 'Koordinator Keamanan (2)',
    category: 'koordinator',
    person_name: 'Alvino Revan Milano',
    student_id: 'std-05',
    position_order: 14,
    badge: 'Ketertiban & Keamanan',
  },
  {
    id: 'role-15',
    role_name: 'Koordinator Keamanan (3)',
    category: 'koordinator',
    person_name: 'Juan Goklas Panjaitan',
    student_id: 'std-21',
    position_order: 15,
    badge: 'Ketertiban & Keamanan',
  },
  // Koordinator Keagamaan
  {
    id: 'role-16',
    role_name: 'Koordinator Keagamaan (1)',
    category: 'koordinator',
    person_name: 'Mahabbah Mahabban Romadhon',
    student_id: 'std-25',
    position_order: 16,
    badge: 'Keagamaan & Rohani',
  },
  {
    id: 'role-17',
    role_name: 'Koordinator Keagamaan (2)',
    category: 'koordinator',
    person_name: 'Luna Almaghfira Nazhifa',
    student_id: 'std-24',
    position_order: 17,
    badge: 'Keagamaan & Rohani',
  },
  {
    id: 'role-18',
    role_name: 'Koordinator Keagamaan (3)',
    category: 'koordinator',
    person_name: 'Alvino Daniswara Mahendra',
    student_id: 'std-04',
    position_order: 18,
    badge: 'Keagamaan & Rohani',
  },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-01',
    title: 'Persiapan Uji Kompetensi Keahlian (UKK) Jaringan Komputer',
    content: `Diberitahukan kepada seluruh siswa kelas XII TKJ bahwa pelaksanaan simulasi Uji Kompetensi Keahlian (UKK) klaster Konfigurasi Routing Dinamis BGP & OSPF serta Implementasi Firewall Server akan dimulai pekan depan.\n\nHarap memastikan setiap siswa telah menyelesaikan tugas portofolio konfigurasi MikroTik dan Cisco Packet Tracer. Buku catatan laboratorium wajib dikumpulkan ke Sekretaris paling lambat hari Jumat.`,
    category: 'Akademik',
    cover_url: '',
    author: 'Bu Febriyana, S.T.',
    is_published: true,
    published_at: '2026-09-18T08:00:00Z',
    created_at: '2026-09-18T08:00:00Z',
    updated_at: '2026-09-18T08:00:00Z',
  },
  {
    id: 'ann-02',
    title: 'Iuran Kas Kelas Bulan Ini & Laporan Transparansi Keuangan',
    content: `Teman-teman XII TKJ, diingatkan untuk melunasi iuran kas kelas bulan September sebesar Rp 15.000 kepada Bendahara (Malaeka atau Maylafiana).\n\nDana kas ini dialokasikan untuk pengadaan toolkit crimping RJ45 bersama, kabel UTP Cat6 praktikum, serta operasional kegiatan kelas. Laporan rekap keuangan digital dapat dicek transparan kapan saja.`,
    category: 'Keuangan',
    cover_url: '',
    author: 'Bendahara Kelas',
    is_published: true,
    published_at: '2026-09-15T09:30:00Z',
    created_at: '2026-09-15T09:30:00Z',
    updated_at: '2026-09-15T09:30:00Z',
  },
  {
    id: 'ann-03',
    title: 'Jadwal Piket Laboratorium Komputer & Kebersihan Ruang Kelas',
    content: `Koordinator Kebersihan (Firjatullah, Galuh, Fabian) telah merilis rotasi jadwal piket laboratorium TKJ 2 dan ruang kelas XII. Seluruh regu piket wajib hadir 20 menit sebelum jam pertama untuk merapikan workstation, mematikan sakelar server setelah jam praktik, dan membersihkan area belajar.`,
    category: 'Kedisiplinan',
    cover_url: '',
    author: 'Koordinator Kebersihan',
    is_published: true,
    published_at: '2026-09-10T07:15:00Z',
    created_at: '2026-09-10T07:15:00Z',
    updated_at: '2026-09-10T07:15:00Z',
  },
];

export const INITIAL_EVENTS: EventItem[] = [
  {
    id: 'ev-01',
    title: 'Simulasi UKK TKJ: MikroTik & Fiber Optic Splicing',
    description: 'Praktikum intensif konfigurasi router board dan penyambungan kabel fiber optik untuk persiapan sertifikasi kompetensi.',
    event_date: '2026-09-25',
    event_time: '07:30 - 14:00 WIB',
    location: 'Laboratorium Jaringan 2',
    category: 'ujian',
    person_in_charge: 'Bu Febriyana, S.T. & Anindito Aziz',
    status: 'upcoming',
    created_at: '2026-09-15T00:00:00Z',
    updated_at: '2026-09-15T00:00:00Z',
  },
  {
    id: 'ev-02',
    title: 'Kunjungan Industri & Workshop Data Center Cloud',
    description: 'Kunjungan edukasi teknologi ke fasilitas Tier-3 Data Center untuk memahami arsitektur server fisik, pendingin presisi, dan sistem UPS cadangan.',
    event_date: '2026-10-08',
    event_time: '08:00 - 15:30 WIB',
    location: 'Cyber Data Center Hub',
    category: 'kegiatan',
    person_in_charge: 'Aloysius Christian & Maheswara Shoofian',
    status: 'upcoming',
    created_at: '2026-09-15T00:00:00Z',
    updated_at: '2026-09-15T00:00:00Z',
  },
  {
    id: 'ev-03',
    title: 'Rapat Koordinasi Persiapan Buku Tahunan & Foto Angkatan',
    description: 'Pembahasan konsep foto kelas, pemilihan tema cyber-tech suit, dan penentuan jadwal sesi pemotretan.',
    event_date: '2026-09-28',
    event_time: '14:30 - 16:00 WIB',
    location: 'Ruang Kelas XII TKJ',
    category: 'rapat',
    person_in_charge: 'Zhafira Naura & Irsyad Zakie',
    status: 'upcoming',
    created_at: '2026-09-15T00:00:00Z',
    updated_at: '2026-09-15T00:00:00Z',
  },
  {
    id: 'ev-04',
    title: 'Pembersihan Besar (Bakti Bersih) Lab Komputer & Server Rack',
    description: 'Perawatan berkala perangkat server, perapihan kabel patch cord di patch panel rack 42U, dan pembersihan filter debu pendingin.',
    event_date: '2026-10-02',
    event_time: '13:00 - 15:00 WIB',
    location: 'Server Room TKJ',
    category: 'piket',
    person_in_charge: 'Firjatullah & Tim Kebersihan',
    status: 'upcoming',
    created_at: '2026-09-15T00:00:00Z',
    updated_at: '2026-09-15T00:00:00Z',
  },
];

export const INITIAL_GALLERY: GalleryItem[] = [
  {
    id: 'gal-01',
    title: 'Praktik Penyambungan Kabel Fiber Optic (Fusion Splicer)',
    image_url: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?q=80&w=1200&auto=format&fit=crop',
    category: 'Praktik TKJ',
    caption: 'Siswa XII TKJ mempraktikkan pengupasan core fiber optic dan pengelasan menggunakan Fusion Splicer dengan redaman di bawah 0.02 dB.',
    uploaded_by: 'Admin',
    created_at: '2026-08-20T10:00:00Z',
  },
  {
    id: 'gal-02',
    title: 'Instalasi Server Rack 42U & Manajemen Patch Cord',
    image_url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=1200&auto=format&fit=crop',
    category: 'Praktik TKJ',
    caption: 'Manajemen kabel rapi (cable management) pada switch manageable dan server rack di laboratorium jaringan.',
    uploaded_by: 'Admin',
    created_at: '2026-08-25T11:00:00Z',
  },
  {
    id: 'gal-03',
    title: 'Kebersamaan Kelas: Diskusi Santai & Brainstorming Project',
    image_url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=1200&auto=format&fit=crop',
    category: 'Kebersamaan',
    caption: 'Momen kolaborasi tim XII TKJ saat merancang arsitektur jaringan skala kampus untuk tugas akhir.',
    uploaded_by: 'Admin',
    created_at: '2026-09-02T14:30:00Z',
  },
  {
    id: 'gal-04',
    title: 'Upacara Peringatan Hari Kemerdekaan bersama Danton Kelas',
    image_url: 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?q=80&w=1200&auto=format&fit=crop',
    category: 'Sekolah',
    caption: 'Pasukan kelas XII TKJ dipimpin oleh Danton Maheswara dan Second Danton Deanda dalam formasi barisan rapi.',
    uploaded_by: 'Admin',
    created_at: '2026-08-17T09:00:00Z',
  },
  {
    id: 'gal-05',
    title: 'Sesi Debugging Routing BGP & Konfigurasi VLAN',
    image_url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=1200&auto=format&fit=crop',
    category: 'Praktik TKJ',
    caption: 'Konsentrasi tinggi saat memecahkan skenario troubleshooting routing loop pada simulasi jaringan enterprise.',
    uploaded_by: 'Admin',
    created_at: '2026-09-12T13:00:00Z',
  },
  {
    id: 'gal-06',
    title: 'Class Project Showcase: IoT Monitoring & Server Automation',
    image_url: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?q=80&w=1200&auto=format&fit=crop',
    category: 'Event',
    caption: 'Presentasi prototipe Smart Server Room Monitoring berbasis ESP32 dan MQTT broker di hadapan penguji dan wali kelas.',
    uploaded_by: 'Admin',
    created_at: '2026-09-14T15:00:00Z',
  },
];

export const INITIAL_TIME_CAPSULES: TimeCapsuleMessage[] = [
  {
    id: 'capsule-1',
    sender_name: 'Daffa Haidar Firmansyah',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=Daffa',
    title: 'Surat Rahasia untuk Network Architect 2030',
    target_year: 2030,
    message: 'Semoga di tahun 2030 kita semua sudah memegang sertifikasi CCIE / MTCINE, bekerja di industri enterprise idaman, dan kumpul reuni akbar mengenang masa-masa begadang praktikum jaringan!',
    created_at: '2026-09-01T08:00:00Z',
    is_locked: true,
  },
  {
    id: 'capsule-2',
    sender_name: 'Alfina Rahmawati & Maylafiana',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=Alfina',
    title: 'Reuni Akbar & Nostalgia Crimping Kabel',
    target_year: 2030,
    message: 'Janji ya teman-teman, tahun 2030 kita wajib meetup bareng Bu Febriyana, cerita tentang karir masing-masing dan recreate foto angkatan di depan rak server!',
    created_at: '2026-09-05T10:30:00Z',
    is_locked: true,
  },
  {
    id: 'capsule-3',
    sender_name: 'Maheswara & Gabriel',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=Gabriel',
    title: 'Sumpah Persaudaraan XII TKJ',
    target_year: 2030,
    message: 'Jangan sampai lost contact. Apapun jalan karir yang kita pilih nanti, kita pernah satu router, satu subnet, dan satu keluarga besar!',
    created_at: '2026-09-10T14:15:00Z',
    is_locked: true,
  },
];

export const INITIAL_MEMORY_NOTES: MemoryNote[] = [
  {
    id: 'mem-1',
    sender_name: 'Bu Febriyana, S.T.',
    role_or_relation: 'Wali Kelas XII TKJ',
    message: 'Banggalah menjadi bagian dari XII TKJ. Kalian adalah angkatan yang tangguh, kreatif, dan penuh potensi. Jaga terus kekompakan dan integritas di manapun kalian berada.',
    color: '#f2eb87',
    likes: 48,
    created_at: '2026-09-15T08:00:00Z',
  },
  {
    id: 'mem-2',
    sender_name: 'Alumni Angkatan 2025',
    role_or_relation: 'Kakak Tingkat',
    message: 'Semangat menghadapi UKK dan ujian akhir buat adik-adik XII TKJ! Jangan tegang pas uji konfigurasi router, kalian pasti bisa!',
    color: '#f5f1ca',
    likes: 32,
    created_at: '2026-09-16T11:20:00Z',
  },
  {
    id: 'mem-3',
    sender_name: 'Pengurus OSIS',
    role_or_relation: 'Sahabat Organisasi',
    message: 'Kelas XII TKJ selalu jadi andalan kalau urusan live streaming dan audio sekolah lancar jaya. Sukses terus kawan!',
    color: '#d8d6c6',
    likes: 27,
    created_at: '2026-09-17T14:45:00Z',
  },
  {
    id: 'mem-4',
    sender_name: 'Anak Pojok Lab',
    role_or_relation: 'Siswa XII TKJ',
    message: 'Momen paling epic adalah saat kabel tester nyala 1 sampai 8 berurutan hijau semua di percobaan pertama!',
    color: '#f2eb87',
    likes: 54,
    created_at: '2026-09-18T16:00:00Z',
  },
];

export const INITIAL_SUPERLATIVES: SuperlativeAward[] = [
  {
    id: 'sup-1',
    title: 'Si Paling Mikrotik & Crimping Kilat',
    category: 'Teknikal Kejuruan',
    student_name: 'Daffa Haidar Firmansyah',
    badge_icon: 'Zap',
    description: 'Kecepatan crimping kabel UTP Cat6 di bawah 90 detik dengan hasil tester 100% sempurna tanpa cela.',
    votes: 31,
  },
  {
    id: 'sup-2',
    title: 'Si Paling Dermawan Hotspot Portable',
    category: 'Karakter Sosial',
    student_name: 'Gabriel Putra Pamungkas',
    badge_icon: 'Wifi',
    description: 'Penyelamat seisi kelas ketika Wi-Fi lab sedang maintenance dengan kuota tak terbatas dan senyum ramah.',
    votes: 34,
  },
  {
    id: 'sup-3',
    title: 'Si Paling Public Speaker & Negosiator',
    category: 'Kepemimpinan',
    student_name: 'Alfina Rahmawati',
    badge_icon: 'Mic',
    description: 'Diplomat ulung kelas saat mempresentasikan project akhir dan bernegosiasi batas akhir pengumpulan tugas praktikum.',
    votes: 29,
  },
  {
    id: 'sup-4',
    title: 'Troubleshooting Master & Debugger Alami',
    category: 'Teknikal Kejuruan',
    student_name: 'Muhammad Neo Navaz Nurvagus',
    badge_icon: 'Cpu',
    description: 'Sekali lirik lampu indikator switch dan routing table langsung tahu di mana titik loop atau IP clash berada.',
    votes: 28,
  },
  {
    id: 'sup-5',
    title: 'Danton Paling Tegas & Karismatik',
    category: 'Keteladanan',
    student_name: 'Maheswara Ceta Pradipa',
    badge_icon: 'Shield',
    description: 'Komandan barisan yang selalu memastikan disiplin formasi upacara bendera dan kekompakan angkatan.',
    votes: 33,
  },
  {
    id: 'sup-6',
    title: 'Si Paling Desainer & Visual Wizard',
    category: 'Kreativitas',
    student_name: 'Maylafiana Nurrizkia S.',
    badge_icon: 'Sparkles',
    description: 'Sentuhan estetik di balik setiap poster acara, feed Instagram kelas, dan dokumentasi visual angkatan.',
    votes: 30,
  },
];

export const INITIAL_CLASS_MEMORIES: ClassMemoryPhoto[] = [
  {
    id: 'mem-photo-1',
    title: 'Praktikum Konfigurasi MikroTik Router & Firewall',
    caption: 'Momen serius saat pengujian routing dinamis OSPF dan firewall filter di Lab Jaringan 1.',
    image_url: 'https://images.unsplash.com/photo-1544717305-2782549b5136?q=80&w=800&auto=format&fit=crop',
    date: '2026-08-14',
    location: 'Lab Jaringan 1',
  },
  {
    id: 'mem-photo-2',
    title: 'Workshop Splicing & OTDR Fiber Optic',
    caption: 'Pelatihan penyambungan serat optik presisi tinggi dan pengukuran loss redaman dB.',
    image_url: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?q=80&w=800&auto=format&fit=crop',
    date: '2026-09-02',
    location: 'Lab Fiber Optic',
  },
  {
    id: 'mem-photo-3',
    title: 'Kebersamaan Pasca Class Meeting & Olahraga',
    caption: 'Keringat dan tawa riang merayakan kemenangan tim futsal XII TKJ bersama suporter kompak.',
    image_url: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?q=80&w=800&auto=format&fit=crop',
    date: '2026-09-18',
    location: 'Lapangan Utama',
  },
  {
    id: 'mem-photo-4',
    title: 'Uji Coba Cluster Virtualisasi Proxmox & Docker',
    caption: 'Diskusi malam penyelesaian deployment server private cloud angkatan XII TKJ.',
    image_url: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?q=80&w=800&auto=format&fit=crop',
    date: '2026-09-25',
    location: 'Ruang Server TKJ',
  },
];

export const INITIAL_DAILY_SCHEDULES: DayScheduleItem[] = [
  {
    dayNumber: 1,
    dayName: 'Senin',
    picketTeam: ['Daffa Haidar F.', 'Gabriel Putra P.', 'Aditiya Putra P.', 'Alfina Rahmawati', 'Anggun Desi N.'],
    motto: 'Kebersihan dan kerapian laboratorium adalah cermin kedisiplinan seorang teknisi jaringan.',
    subjects: [
      { id: 'sub-1-1', time: '07:00 - 07:45', subject: 'Upacara Bendera', teacher: 'Pembina OSIS', room: 'Lapangan Utama', block: 'teori' },
      { id: 'sub-1-2', time: '07:45 - 10:00', subject: 'Administrasi Infrastruktur Jaringan (MikroTik)', teacher: 'Bu Febriyana, S.T.', room: 'Lab Jaringan 1', block: 'praktik' },
      { id: 'sub-1-3', time: '10:15 - 12:30', subject: 'Teknologi Layanan Jaringan (VoIP)', teacher: 'Pak Haryanto, M.Kom.', room: 'Lab Komputer 2', block: 'praktik' },
      { id: 'sub-1-4', time: '13:00 - 15:00', subject: 'Bahasa Indonesia', teacher: 'Bu Siti Rahma, M.Pd.', room: 'Ruang XII TKJ', block: 'teori' },
    ],
  },
  {
    dayNumber: 2,
    dayName: 'Selasa',
    picketTeam: ['Anisa Septiana', 'Antika Desy S.', 'Aulia Fatimatuz Z.', 'Azura Khoirun N.', 'Deanda Aji R.'],
    motto: 'Laboratorium bersih, praktikum lancar tanpa debu pada server dan switch.',
    subjects: [
      { id: 'sub-2-1', time: '07:00 - 10:00', subject: 'Keamanan Jaringan & Cyber Security', teacher: 'Pak Aris Santoso, S.Kom.', room: 'Lab Security', block: 'praktik' },
      { id: 'sub-2-2', time: '10:15 - 12:30', subject: 'Teknologi Jaringan Berbasis Luas (WAN & FO)', teacher: 'Bu Febriyana, S.T.', room: 'Lab Fiber Optic', block: 'praktik' },
      { id: 'sub-2-3', time: '13:00 - 15:00', subject: 'Pendidikan Agama & Budi Pekerti', teacher: 'Pak Ahmad Zaki, M.Ag.', room: 'Ruang XII TKJ', block: 'teori' },
    ],
  },
  {
    dayNumber: 3,
    dayName: 'Rabu',
    picketTeam: ['Dwiki Rifqi P.', 'Dyah Retno A.', 'Fathurrizqy Z. A.', 'Gilang Surya S.', 'Haqi Hafizh A.'],
    motto: 'Ruang yang rapi menumbuhkan ide-ide konfigurasi dan arsitektur yang cemerlang.',
    subjects: [
      { id: 'sub-3-1', time: '07:00 - 09:30', subject: 'Produk Kreatif & Kewirausahaan (IoT Showcase)', teacher: 'Bu Sri Wahyuni, S.E.', room: 'Lab IoT', block: 'praktik' },
      { id: 'sub-3-2', time: '09:45 - 12:00', subject: 'Administrasi Sistem Jaringan (Debian Server)', teacher: 'Pak Danang W., S.T.', room: 'Lab Server Room', block: 'praktik' },
      { id: 'sub-3-3', time: '12:45 - 14:45', subject: 'Bahasa Inggris Kejuruan', teacher: 'Mr. David Wilson, M.Ed.', room: 'Ruang XII TKJ', block: 'teori' },
    ],
  },
  {
    dayNumber: 4,
    dayName: 'Kamis',
    picketTeam: ['Khoirul Azam', 'Lutfiana Rahma', 'Maheswara Ceta P.', 'Maylafiana Nurrizkia', 'Muhammad Neo Navaz'],
    motto: 'Merawat sarana kelas adalah wujud nyata kepedulian terhadap almamater.',
    subjects: [
      { id: 'sub-4-1', time: '07:00 - 10:00', subject: 'Praktikum Cloud Computing & Virtualisasi', teacher: 'Pak Danang W., S.T.', room: 'Lab Cloud', block: 'praktik' },
      { id: 'sub-4-2', time: '10:15 - 12:30', subject: 'Matematika Terapan', teacher: 'Bu Retno Kusuma, M.Pd.', room: 'Ruang XII TKJ', block: 'teori' },
      { id: 'sub-4-3', time: '13:00 - 15:00', subject: 'Pendidikan Pancasila', teacher: 'Pak Bambang S., S.Pd.', room: 'Ruang XII TKJ', block: 'teori' },
    ],
  },
  {
    dayNumber: 5,
    dayName: 'Jumat',
    picketTeam: ['Nur Muhibbin', 'Oreal Ahessa W.', 'Rehan Prasetyo', 'Salwa Aulia P.', 'Zahra Kurniawati'],
    motto: 'Jumat berkah, tinggalkan laboratorium dalam kondisi bersih siap pakai untuk pekan berikutnya.',
    subjects: [
      { id: 'sub-5-1', time: '07:00 - 08:00', subject: 'Senam Pagi & Literasi Digital', teacher: 'Keluarga Sekolah', room: 'Lapangan', block: 'teori' },
      { id: 'sub-5-2', time: '08:00 - 10:30', subject: 'Simulasi UKK & Troubleshooting Jaringan', teacher: 'Bu Febriyana & Tim Penguji', room: 'Lab Core TKJ', block: 'praktik' },
      { id: 'sub-5-3', time: '10:30 - 11:30', subject: 'Evaluasi Mingguan Kelas & Wali Kelas', teacher: 'Bu Febriyana, S.T.', room: 'Ruang XII TKJ', block: 'teori' },
    ],
  },
];

export const INITIAL_PROJECTS: ClassProject[] = [
  {
    id: 'proj-01',
    name: 'NetWatch',
    slug: 'netwatch',
    short_description: 'Network monitoring platform untuk memantau status layanan, bandwidth, dan konektivitas router secara real-time.',
    full_description: 'NetWatch adalah solusi terintegrasi untuk pengawasan jaringan skala sekolah dan lab komputer. Menggunakan arsitektur WebSocket berkecepatan tinggi, NetWatch mampu mendeteksi downtime node, latensi tinggi, dan lonjakan penggunaan bandwidth dalam hitungan detik dengan visualisasi grafik interaktif.',
    cover_url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=1200&auto=format&fit=crop',
    student_creator: 'Mahabbah & Team',
    team_members: ['Mahabbah', 'Ahmad Faiz', 'Bima Sakti', 'Dafa Pratama'],
    category: 'Network',
    tech_stack: ['Flutter', 'FastAPI', 'WebSocket', 'RouterOS API'],
    year: '2026',
    status: 'Completed',
    github_url: 'https://github.com/kangguruhdq-ux/netwatch',
    demo_url: 'https://netwatch.preview.app',
    key_features: [
      'Pemantauan utilisasi bandwidth per antarmuka secara live',
      'Peringatan otomatis downtime router via bot Telegram',
      'Peta topologi jaringan interaktif dengan status probe',
      'Manajemen log histori latency dan packet loss',
    ],
    screenshots: [
      'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1200&auto=format&fit=crop',
    ],
    is_published: true,
    is_featured: true,
    display_order: 1,
    created_at: '2026-08-10T00:00:00Z',
    updated_at: '2026-09-15T00:00:00Z',
  },
  {
    id: 'proj-02',
    name: 'FixTown',
    slug: 'fixtown',
    short_description: 'Platform pelaporan masalah fasilitas publik dan pengelolaan tindak lanjut terintegrasi geolokasi.',
    full_description: 'FixTown dirancang untuk mempercepat perbaikan fasilitas publik maupun lingkungan sekolah. Siswa atau warga dapat memotret fasilitas yang rusak, melampirkan titik koordinat GPS otomatis, dan memantau progres perbaikan dari tim teknisi secara transparan.',
    cover_url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=1200&auto=format&fit=crop',
    student_creator: 'Dimas & Team',
    team_members: ['Dimas Saputra', 'Galang Ramadhan', 'Farhan Kurnia', 'Ilham Prasetyo'],
    category: 'Mobile App',
    tech_stack: ['Flutter', 'FastAPI', 'PostgreSQL', 'SQLAlchemy'],
    year: '2026',
    status: 'Completed',
    github_url: 'https://github.com/kangguruhdq-ux/fixtown',
    demo_url: 'https://fixtown.preview.app',
    apk_url: 'https://github.com/kangguruhdq-ux/fixtown/releases',
    key_features: [
      'Penandaan lokasi GPS otomatis dengan peta interaktif',
      'Unggah foto bukti sebelum dan sesudah perbaikan',
      'Sistem tiket laporan dengan status Terkirim, Dikerjakan, Selesai',
      'Dashboard statistik keluhan dan efektivitas perbaikan',
    ],
    screenshots: [
      'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?q=80&w=1200&auto=format&fit=crop',
    ],
    is_published: true,
    is_featured: true,
    display_order: 2,
    created_at: '2026-08-18T00:00:00Z',
    updated_at: '2026-09-18T00:00:00Z',
  },
  {
    id: 'proj-03',
    name: 'Aegis AI',
    slug: 'aegis-ai',
    short_description: 'Platform analisis risiko bencana dan deteksi anomali trafik jaringan berbasis machine learning.',
    full_description: 'Aegis AI mengkombinasikan analitik prediktif dan machine learning untuk mendeteksi ancaman intrusi siber seperti SYN flood dan port scanning, sekaligus menyediakan modul pemodelan evakuasi bencana lingkungan sekolah.',
    cover_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1200&auto=format&fit=crop',
    student_creator: 'Fajar & Team',
    team_members: ['Fajar Hidayat', 'Kevin Maulana', 'Naufal Rizky', 'Rizky Pratama'],
    category: 'AI / Machine Learning',
    tech_stack: ['React', 'Python FastAPI', 'TensorFlow', 'Scikit-Learn'],
    year: '2026',
    status: 'In Development',
    github_url: 'https://github.com/kangguruhdq-ux/aegis-ai',
    demo_url: 'https://aegis-ai.preview.app',
    key_features: [
      'Deteksi paket anomali zero-day dengan akurasi 96.4%',
      'Visualisasi matriks korelasi fitur trafik jaringan',
      'Ekspor laporan insiden otomatis format PDF',
    ],
    screenshots: [
      'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1200&auto=format&fit=crop',
    ],
    is_published: true,
    is_featured: true,
    display_order: 3,
    created_at: '2026-08-25T00:00:00Z',
    updated_at: '2026-09-19T00:00:00Z',
  },
  {
    id: 'proj-04',
    name: 'MikroShield Auditor',
    slug: 'mikroshield',
    short_description: 'Automated firewall rule manager & security compliance auditor untuk router sekolah.',
    full_description: 'MikroShield mempermudah network engineer sekolah dalam menerapkan best practice keamanan MikroTik RouterOS. Secara otomatis mengecek port default, brute-force defense, dan DNS amplification blocker.',
    cover_url: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?q=80&w=1200&auto=format&fit=crop',
    student_creator: 'Haidar & Team',
    team_members: ['Haidar Ali', 'Danu Wijaya', 'Eko Prasetyo'],
    category: 'Cyber Security',
    tech_stack: ['Next.js', 'RouterOS API', 'TailwindCSS'],
    year: '2026',
    status: 'Completed',
    github_url: 'https://github.com/kangguruhdq-ux/mikroshield',
    demo_url: 'https://mikroshield.preview.app',
    key_features: [
      'Audit otomatis skor keamanan router dari skala 0-100',
      'One-click remediation untuk blokir port rawan',
      'Backup konfigurasi terjadwal terenkripsi',
    ],
    screenshots: [
      'https://images.unsplash.com/photo-1563986768609-322da13575f3?q=80&w=1200&auto=format&fit=crop',
    ],
    is_published: true,
    is_featured: false,
    display_order: 4,
    created_at: '2026-09-01T00:00:00Z',
    updated_at: '2026-09-17T00:00:00Z',
  },
  {
    id: 'proj-05',
    name: 'SmartLab IoT Matrix',
    slug: 'smartlab-iot',
    short_description: 'Sistem monitoring suhu, kelembaban, dan otomasi daya terdistribusi di laboratorium komputer XII TJ.',
    full_description: 'Sistem otomasi IoT yang menghubungkan mikrokontroler ESP32 dengan sensor DHT22 dan relay power management untuk memastikan ruang server dan lab TKJ selalu pada suhu dan daya optimal.',
    cover_url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1200&auto=format&fit=crop',
    student_creator: 'Bima & Team',
    team_members: ['Bima Sakti', 'Faris Ihsan', 'Yoga Pratama'],
    category: 'IoT',
    tech_stack: ['ESP32', 'MQTT', 'Node-RED', 'React'],
    year: '2026',
    status: 'Completed',
    github_url: 'https://github.com/kangguruhdq-ux/smartlab-iot',
    demo_url: 'https://smartlab.preview.app',
    key_features: [
      'Telemetri suhu dan kelembaban 24/7 via broker MQTT',
      'Saklar daya komputer remote via web interface',
      'Notifikasi otomatis bahaya overheat ruang server',
    ],
    screenshots: [
      'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1200&auto=format&fit=crop',
    ],
    is_published: true,
    is_featured: false,
    display_order: 5,
    created_at: '2026-09-05T00:00:00Z',
    updated_at: '2026-09-18T00:00:00Z',
  },
];

export const INITIAL_SETTINGS: SiteSettings = {
  id: 'settings-singleton',
  class_name: 'XII TJ',
  class_subtitle: 'Teknik Komputer dan Jaringan',
  academic_year: '2026/2027',
  tagline: 'ANGKATAN 27 — XII TJ',
  description: 'Portal resmi XII TJ (Teknik Komputer dan Jaringan) Angkatan 27. Wadah kebersamaan, persaudaraan, dan showcase karya teknologi siswa.',
  logo_url: '', // Default svg cyber icon is rendered if empty
  hero_image_url: '', // High-tech cyber canvas is rendered if empty
  favicon_url: '/favicon.ico',
  homeroom_teacher: 'Bu Febriyana, S.T.',
  instagram_url: 'https://www.instagram.com/networkengineering27?stkn=bnB4dnY1dHRjcDZ3',
  tiktok_url: 'https://www.tiktok.com/@networkcomp.27?_r=1&_t=ZS-99sUSsU8y0t',
  github_url: 'https://github.com',
  youtube_url: 'https://youtube.com',
  contact_email: 'tkj.duabelas@sekolah.sch.id',
  admin_password: 'admin',
  active_ai_provider: 'mock',
  ai_bot_name: 'Ping-Ping si Kucing Router',
  gemini_api_key: '',
  groq_api_key: '',
  openrouter_api_key: '',

  // Milestone Countdown Defaults
  milestone_ukk_title: 'Uji Kompetensi Keahlian (UKK)',
  milestone_ukk_subtitle: 'Sertifikasi Praktik TKJ 2027',
  milestone_ukk_date: '2027-02-20T08:00:00Z',
  milestone_ukk_badge: 'Februari 2027',
  milestone_ukk_desc: 'Fokus menguasai routing BGP, MikroTik firewall, dan splicing fiber optic menuju kelulusan standar industri!',
  milestone_wisuda_title: 'Puncak Angkatan 27',
  milestone_wisuda_subtitle: 'Wisuda & Pelepasan XII TJ',
  milestone_wisuda_date: '2027-06-15T08:00:00Z',
  milestone_wisuda_badge: 'Juni 2027',
  milestone_wisuda_desc: 'Menghitung setiap detik kebersamaan, tawa di lorong kelas, dan persaudaraan selamanya sebagai Angkatan 27 XII TJ!',

  // Foto Kenangan & Foto Kelas (/tentang)
  class_photo_url: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?q=80&w=1200&auto=format&fit=crop',
  class_photo_title: 'Foto Bersama Keluarga Besar XII TJ Angkatan 27',
  class_photo_description: 'Potret kebersamaan 34 siswa bersama Wali Kelas Bu Febriyana, S.T. di laboratorium komputer dan jaringan sekolah.',
  class_memories: INITIAL_CLASS_MEMORIES,

  updated_at: '2026-09-20T00:00:00Z',
};

export const INITIAL_LAB_SETTINGS: LabSettings = {
  page_title: 'Denah Meja Kelas & Lab XII TKJ',
  page_subtitle: 'Visualisasi penataan tempat duduk praktikum dan workstation komputer jaringan 34 siswa keluarga besar XII TKJ.',
  server_rack_name: 'Core Rack Server',
  server_rack_desc: 'MikroTik CCR + 48P Switch',
  board_title: 'PAPAN TULIS & LAYAR PROYEKTOR UTAMA',
  board_desc: 'Area Pengajaran & Presentasi Praktik Jaringan',
  podium_title: 'Podium Pembimbing',
  podium_teacher: 'Bu Febriyana, S.T.',
};

export const INITIAL_SEATING_PLAN: DeskItem[] = Array.from({ length: 17 }, (_, idx) => {
  const deskNum = idx + 1;
  const s1 = INITIAL_STUDENTS[idx * 2];
  const s2 = INITIAL_STUDENTS[idx * 2 + 1];
  return {
    id: `desk-${deskNum}`,
    deskNum,
    vlan: 10 + deskNum,
    seatA: {
      student_id: s1?.id || '',
      student_name: s1?.name || `Siswa ${idx * 2 + 1}`,
      ip_address: `192.168.27.${deskNum * 2}`,
      pc_name: `PC-TJ-${String(deskNum).padStart(2, '0')}A`,
      status: 'online' as const,
    },
    seatB: {
      student_id: s2?.id || '',
      student_name: s2?.name || `Siswa ${idx * 2 + 2}`,
      ip_address: `192.168.27.${deskNum * 2 + 1}`,
      pc_name: `PC-TJ-${String(deskNum).padStart(2, '0')}B`,
      status: 'online' as const,
    },
    notes: `Workstation Praktik Meja #${deskNum} (VLAN ${10 + deskNum})`,
  };
});

export const INITIAL_CMS_DATA: CMSData = {
  version: 'tkj_cms_v1',
  timestamp: 1758355200000,
  students: INITIAL_STUDENTS,
  roles: INITIAL_ROLES,
  announcements: INITIAL_ANNOUNCEMENTS,
  events: INITIAL_EVENTS,
  gallery: INITIAL_GALLERY,
  settings: INITIAL_SETTINGS,
  projects: INITIAL_PROJECTS,
  time_capsules: INITIAL_TIME_CAPSULES,
  memory_notes: INITIAL_MEMORY_NOTES,
  superlatives: INITIAL_SUPERLATIVES,
  daily_schedules: INITIAL_DAILY_SCHEDULES,
  seating_plan: INITIAL_SEATING_PLAN,
  lab_settings: INITIAL_LAB_SETTINGS,
};
